twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        locales: '%app.supported_locales%'
        dnsServer: '%dnsServer%'
        concat_local_address: '%env(CONCAT_LOCAL_ADDRESS)%'
        struct_province_country_city: '%env(STRUCT_PROVINCE_COUNTRY_CITY)%'
        prefecture_between_region_city: '%env(PREFECTURE_BETWEEN_REGION_CITY)%'
        app_version: '%app_version%'
        persondegree_types: '@App\Services\PersonDegreeTypes'

when@test:
    twig:
        strict_variables: true
