version: '3'
services:
  app:
    build: .
    container_name: inserjeune-v2
    volumes:
      - ./:/home/inserjeune
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "8090:8000"
    expose:
      - 9000
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql-inserjeune-v2
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: inserjeune
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma-inserjeune-v2
    depends_on:
      -   mysql
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-inserjeune-v2
      UPLOAD_LIMIT: 900M
#  mailer:
#    image: schickling/mailcatcher
#    ports: [1025, 1080]

volumes:
  db_data: {}
