<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220917124116 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE JobNotFoundReasonRepository (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE activity_sector_area (sector_area_id INT NOT NULL, id_sectorArea INT NOT NULL, INDEX IDX_F742885279B02DB (id_sectorArea), INDEX IDX_F7428851782D3BB (sector_area_id), PRIMARY KEY(id_sectorArea, sector_area_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE apprentice (id INT AUTO_INCREMENT NOT NULL, activity_id INT DEFAULT NULL, contract_id INT DEFAULT NULL, company_id INT DEFAULT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, id_image INT DEFAULT NULL, monthly_salary INT NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, birth_date DATETIME NOT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, phone_mobile1 VARCHAR(255) NOT NULL, phone_mobile2 VARCHAR(255) DEFAULT NULL, phone_mobile3 VARCHAR(255) DEFAULT NULL, phone_home VARCHAR(255) DEFAULT NULL, phone_office VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, sex VARCHAR(10) NOT NULL, INDEX IDX_54C3A96D81C06096 (activity_id), INDEX IDX_54C3A96D2576E0FD (contract_id), INDEX IDX_54C3A96D979B1AD6 (company_id), INDEX IDX_54C3A96DA67B1E36 (id_city), INDEX IDX_54C3A96D2955449B (id_region), INDEX IDX_54C3A96D8DEE6016 (id_country), INDEX IDX_54C3A96D2BB8456F (id_image), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE candidate (id INT AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE candidate_research (id INT AUTO_INCREMENT NOT NULL, status TINYINT(1) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, agree_rgpd TINYINT(1) DEFAULT NULL, last_degree_year INT DEFAULT NULL, last_degree_month INT DEFAULT NULL, other_degree VARCHAR(255) DEFAULT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, client_updated_date DATETIME DEFAULT NULL, previousEndedContract DATETIME DEFAULT NULL, registration_student_school VARCHAR(255) DEFAULT NULL, check_school TINYINT(1) DEFAULT NULL, other_school VARCHAR(255) DEFAULT NULL, monthly_salary INT DEFAULT NULL, other_activity VARCHAR(255) DEFAULT NULL, lastIdSatisfactionSalary INT DEFAULT NULL, lastIdSatisfactionSearch INT DEFAULT NULL, lastIdSatisfactionCreato INT DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, birth_date DATETIME NOT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, phone_mobile1 VARCHAR(255) NOT NULL, phone_mobile2 VARCHAR(255) DEFAULT NULL, phone_mobile3 VARCHAR(255) DEFAULT NULL, phone_home VARCHAR(255) DEFAULT NULL, phone_office VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, sex VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, id_region INT DEFAULT NULL, name VARCHAR(255) NOT NULL, post_code INT DEFAULT NULL, is_capital TINYINT(1) NOT NULL, INDEX IDX_2D5B02342955449B (id_region), UNIQUE INDEX city_region_unique (name, id_region), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, id_legal_status INT DEFAULT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME DEFAULT NULL, client_updated_date DATETIME DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, phone_standard VARCHAR(255) NOT NULL, phone_other VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, location_fixed TINYINT(1) NOT NULL, agree_rgpd TINYINT(1) DEFAULT NULL, id_contactCompany INT DEFAULT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_4FBF094FA67B1E36 (id_city), INDEX IDX_4FBF094F2955449B (id_region), INDEX IDX_4FBF094F8DEE6016 (id_country), INDEX IDX_4FBF094FD4C55DD7 (id_contactCompany), INDEX IDX_4FBF094F279B02DB (id_sectorArea), INDEX IDX_4FBF094FB4F7CA15 (id_legal_status), INDEX IDX_4FBF094FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE companies_socials (company_id INT NOT NULL, social_id INT NOT NULL, INDEX IDX_B4D23109979B1AD6 (company_id), INDEX IDX_B4D23109FFEB5B27 (social_id), PRIMARY KEY(company_id, social_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_creator (id INT AUTO_INCREMENT NOT NULL, status TINYINT(1) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, agree_rgpd TINYINT(1) DEFAULT NULL, last_degree_year INT DEFAULT NULL, last_degree_month INT DEFAULT NULL, other_degree VARCHAR(255) DEFAULT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, client_updated_date DATETIME DEFAULT NULL, previousEndedContract DATETIME DEFAULT NULL, registration_student_school VARCHAR(255) DEFAULT NULL, check_school TINYINT(1) DEFAULT NULL, other_school VARCHAR(255) DEFAULT NULL, monthly_salary INT DEFAULT NULL, other_activity VARCHAR(255) DEFAULT NULL, lastIdSatisfactionSalary INT DEFAULT NULL, lastIdSatisfactionSearch INT DEFAULT NULL, lastIdSatisfactionCreato INT DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, birth_date DATETIME NOT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, phone_mobile1 VARCHAR(255) NOT NULL, phone_mobile2 VARCHAR(255) DEFAULT NULL, phone_mobile3 VARCHAR(255) DEFAULT NULL, phone_home VARCHAR(255) DEFAULT NULL, phone_office VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, sex VARCHAR(10) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact_company (id INT AUTO_INCREMENT NOT NULL, id_contract INT NOT NULL, id_company INT NOT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, id_image INT DEFAULT NULL, job VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, birth_date DATETIME NOT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, phone_mobile1 VARCHAR(255) NOT NULL, phone_mobile2 VARCHAR(255) DEFAULT NULL, phone_mobile3 VARCHAR(255) DEFAULT NULL, phone_home VARCHAR(255) DEFAULT NULL, phone_office VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, sex VARCHAR(10) NOT NULL, INDEX IDX_D59028CEB954C4CC (id_contract), INDEX IDX_D59028CE9122A03F (id_company), INDEX IDX_D59028CEA67B1E36 (id_city), INDEX IDX_D59028CE2955449B (id_region), INDEX IDX_D59028CE8DEE6016 (id_country), INDEX IDX_D59028CE2BB8456F (id_image), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contract (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE country (id INT AUTO_INCREMENT NOT NULL, id_currency INT DEFAULT NULL, valid TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, iso_code VARCHAR(3) NOT NULL, phone_code INT NOT NULL, phone_digit INT NOT NULL, INDEX IDX_5373C966398D64AA (id_currency), UNIQUE INDEX country_name_unique (name), UNIQUE INDEX country_iso_unique (iso_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, iso_name VARCHAR(255) NOT NULL, iso_num VARCHAR(255) NOT NULL, iso_symbol VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE degree (id INT AUTO_INCREMENT NOT NULL, activity_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, level INT NOT NULL, INDEX IDX_A7A36D6381C06096 (activity_id), UNIQUE INDEX degree_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE geo_location (id INT AUTO_INCREMENT NOT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, activity_id INT DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, address_number INT DEFAULT NULL, show_companies TINYINT(1) NOT NULL, show_schools TINYINT(1) NOT NULL, show_person_degrees TINYINT(1) NOT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_B027FE6AA67B1E36 (id_city), INDEX IDX_B027FE6A2955449B (id_region), INDEX IDX_B027FE6A8DEE6016 (id_country), INDEX IDX_B027FE6A81C06096 (activity_id), INDEX IDX_B027FE6A279B02DB (id_sectorArea), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, url VARCHAR(400) NOT NULL, UNIQUE INDEX image_url_unique (url), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE info_creator (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(510) NOT NULL, UNIQUE INDEX UNIQ_3EC3C3FD5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_offer (id INT AUTO_INCREMENT NOT NULL, id_company INT DEFAULT NULL, activity_id INT DEFAULT NULL, lasted_contract_id INT DEFAULT NULL, id_image INT DEFAULT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_date DATETIME DEFAULT NULL, closed_date DATETIME DEFAULT NULL, posted_contact VARCHAR(255) DEFAULT NULL, posted_phone VARCHAR(255) DEFAULT NULL, posted_email VARCHAR(255) NOT NULL, cover_letter VARCHAR(255) DEFAULT NULL, other_activity VARCHAR(255) DEFAULT NULL, filename VARCHAR(255) DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_288A3A4E9122A03F (id_company), INDEX IDX_288A3A4E279B02DB (id_sectorArea), INDEX IDX_288A3A4E81C06096 (activity_id), INDEX IDX_288A3A4ED4CE9F9E (lasted_contract_id), INDEX IDX_288A3A4E2BB8456F (id_image), INDEX IDX_288A3A4EA67B1E36 (id_city), INDEX IDX_288A3A4E2955449B (id_region), INDEX IDX_288A3A4E8DEE6016 (id_country), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE legal_status (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, UNIQUE INDEX legal_status_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE omission_reason (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, level INT DEFAULT NULL, complete_training TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_degree (id INT AUTO_INCREMENT NOT NULL, id_degree INT DEFAULT NULL, school_id INT DEFAULT NULL, lasted_company_id INT DEFAULT NULL, activity_id INT DEFAULT NULL, lasted_contract_id INT DEFAULT NULL, user_id INT DEFAULT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, id_image INT DEFAULT NULL, status TINYINT(1) DEFAULT NULL, type VARCHAR(255) DEFAULT NULL, agree_rgpd TINYINT(1) DEFAULT NULL, last_degree_year INT DEFAULT NULL, last_degree_month INT DEFAULT NULL, other_degree VARCHAR(255) DEFAULT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, client_updated_date DATETIME DEFAULT NULL, previousEndedContract DATETIME DEFAULT NULL, registration_student_school VARCHAR(255) DEFAULT NULL, check_school TINYINT(1) DEFAULT NULL, other_school VARCHAR(255) DEFAULT NULL, monthly_salary INT DEFAULT NULL, other_activity VARCHAR(255) DEFAULT NULL, lastIdSatisfactionSalary INT DEFAULT NULL, lastIdSatisfactionSearch INT DEFAULT NULL, lastIdSatisfactionCreato INT DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, birth_date DATETIME NOT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, other_city VARCHAR(255) DEFAULT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, phone_mobile1 VARCHAR(255) NOT NULL, phone_mobile2 VARCHAR(255) DEFAULT NULL, phone_mobile3 VARCHAR(255) DEFAULT NULL, phone_home VARCHAR(255) DEFAULT NULL, phone_office VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, sex VARCHAR(10) NOT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_3B065DD58194D88E (id_degree), INDEX IDX_3B065DD5C32A47EE (school_id), INDEX IDX_3B065DD5FB063B07 (lasted_company_id), INDEX IDX_3B065DD581C06096 (activity_id), INDEX IDX_3B065DD5279B02DB (id_sectorArea), INDEX IDX_3B065DD5D4CE9F9E (lasted_contract_id), UNIQUE INDEX UNIQ_3B065DD5A76ED395 (user_id), INDEX IDX_3B065DD5A67B1E36 (id_city), INDEX IDX_3B065DD52955449B (id_region), INDEX IDX_3B065DD58DEE6016 (id_country), INDEX IDX_3B065DD52BB8456F (id_image), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE persons_socials (person_id INT NOT NULL, social_id INT NOT NULL, INDEX IDX_EC688D94217BBB47 (person_id), INDEX IDX_EC688D94FFEB5B27 (social_id), PRIMARY KEY(person_id, social_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE person_degree_info_creators (person_degree_id INT NOT NULL, info_creator_id INT NOT NULL, INDEX IDX_FD67B6E2B75B4FC (person_degree_id), INDEX IDX_FD67B6E239E7320A (info_creator_id), PRIMARY KEY(person_degree_id, info_creator_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE profession (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, UNIQUE INDEX profession_name_unique (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE publicity (id INT AUTO_INCREMENT NOT NULL, id_company INT DEFAULT NULL, id_image INT DEFAULT NULL, title VARCHAR(255) NOT NULL, createdDate DATETIME NOT NULL, closedDate DATETIME NOT NULL, INDEX IDX_93812769122A03F (id_company), INDEX IDX_93812762BB8456F (id_image), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reason_satisfied (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE region (id INT AUTO_INCREMENT NOT NULL, id_country INT DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_F62F1768DEE6016 (id_country), UNIQUE INDEX region_name_unique (name, id_country), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (id INT AUTO_INCREMENT NOT NULL, role VARCHAR(100) NOT NULL, UNIQUE INDEX UNIQ_57698A6A57698A6A (role), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_company (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, worker_sector_area_id INT DEFAULT NULL, technician_sector_area_id INT DEFAULT NULL, salary_number VARCHAR(255) NOT NULL, apprentice_number VARCHAR(255) NOT NULL, student_number VARCHAR(255) NOT NULL, other_worker_job VARCHAR(255) DEFAULT NULL, other_technician_job VARCHAR(255) DEFAULT NULL, level_skill VARCHAR(255) NOT NULL, level_global_skill INT NOT NULL, level_technical_skill INT NOT NULL, level_communication_hygiene_health_env_skill INT NOT NULL, level_other_skill INT DEFAULT NULL, level_other_name VARCHAR(255) DEFAULT NULL, other_omission_people VARCHAR(255) DEFAULT NULL, hiring_same_profile TINYINT(1) NOT NULL, complete_training TINYINT(1) NOT NULL, complete_global_training TINYINT(1) NOT NULL, complete_technical_training TINYINT(1) NOT NULL, complete_communication_hygiene_health_env_training TINYINT(1) NOT NULL, complete_Other_training TINYINT(1) NOT NULL, hiring_6_months_worker VARCHAR(255) NOT NULL, hiring_6_months_technician VARCHAR(255) NOT NULL, hiring_6_months_apprentice VARCHAR(255) NOT NULL, hiring_6_months_student VARCHAR(255) NOT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, INDEX IDX_D18F6915979B1AD6 (company_id), INDEX IDX_D18F6915867605F8 (worker_sector_area_id), INDEX IDX_D18F6915BAF32DF3 (technician_sector_area_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_company_activities (satisfaction_company_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_57B2A1B2B594EA25 (satisfaction_company_id), INDEX IDX_57B2A1B281C06096 (activity_id), PRIMARY KEY(satisfaction_company_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_company_technicians_activities (satisfaction_company_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_ABA2E6BBB594EA25 (satisfaction_company_id), INDEX IDX_ABA2E6BB81C06096 (activity_id), PRIMARY KEY(satisfaction_company_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_company_reason (satisfaction_company_id INT NOT NULL, omission_reason_id INT NOT NULL, INDEX IDX_75C87BCBB594EA25 (satisfaction_company_id), INDEX IDX_75C87BCB544EB073 (omission_reason_id), PRIMARY KEY(satisfaction_company_id, omission_reason_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_creator (id INT AUTO_INCREMENT NOT NULL, person_degree_id INT NOT NULL, currency_id INT DEFAULT NULL, other_activity VARCHAR(255) DEFAULT NULL, legal_company TINYINT(1) NOT NULL, monthly_salary INT NOT NULL, useful_training TINYINT(1) NOT NULL, job_not_found_other VARCHAR(255) DEFAULT NULL, degree_date VARCHAR(255) DEFAULT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_22368A39B75B4FC (person_degree_id), INDEX IDX_22368A39279B02DB (id_sectorArea), INDEX IDX_22368A3938248176 (currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_creator_activities (satisfaction_creator_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_92C26FBF432DFE55 (satisfaction_creator_id), INDEX IDX_92C26FBF81C06096 (activity_id), PRIMARY KEY(satisfaction_creator_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_creator_reasons (satisfaction_creator_id INT NOT NULL, job_not_found_reason_id INT NOT NULL, INDEX IDX_B90DBFEB432DFE55 (satisfaction_creator_id), INDEX IDX_B90DBFEB5C785F5D (job_not_found_reason_id), PRIMARY KEY(satisfaction_creator_id, job_not_found_reason_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_salary (id INT AUTO_INCREMENT NOT NULL, person_degree_id INT NOT NULL, id_company INT DEFAULT NULL, currency_id INT DEFAULT NULL, job_not_found_reasons_id INT DEFAULT NULL, lasted_contract_id INT DEFAULT NULL, activity_id INT DEFAULT NULL, monthly_salary INT NOT NULL, dayly_salary INT DEFAULT NULL, company_name VARCHAR(255) NOT NULL, company_city VARCHAR(255) NOT NULL, company_phone VARCHAR(255) NOT NULL, job_name VARCHAR(255) DEFAULT NULL, job_status VARCHAR(255) DEFAULT NULL, job_time DATETIME NOT NULL, work_hours_per_day VARCHAR(255) DEFAULT NULL, job_satisfied TINYINT(1) NOT NULL, training_satisfied TINYINT(1) NOT NULL, job_not_found_other VARCHAR(255) DEFAULT NULL, other_contract VARCHAR(255) DEFAULT NULL, degree_date VARCHAR(255) DEFAULT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, other_activity_name VARCHAR(255) DEFAULT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_C0E64276B75B4FC (person_degree_id), INDEX IDX_C0E642769122A03F (id_company), INDEX IDX_C0E6427638248176 (currency_id), INDEX IDX_C0E64276F2F7E833 (job_not_found_reasons_id), INDEX IDX_C0E64276D4CE9F9E (lasted_contract_id), INDEX IDX_C0E64276279B02DB (id_sectorArea), INDEX IDX_C0E6427681C06096 (activity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_search (id INT AUTO_INCREMENT NOT NULL, sector_area_volunteer_id INT DEFAULT NULL, activity_volunteer_id INT DEFAULT NULL, person_degree_id INT NOT NULL, degree_id INT DEFAULT NULL, registered_training TINYINT(1) NOT NULL, formation_pursuit_last_degree TINYINT(1) NOT NULL, other_formation_degree_name VARCHAR(255) DEFAULT NULL, other_formation_activity_name VARCHAR(255) DEFAULT NULL, search_work TINYINT(1) NOT NULL, no_search_work_reason VARCHAR(255) DEFAULT NULL, active_volunteer TINYINT(1) NOT NULL, other_domain_volunteer VARCHAR(255) DEFAULT NULL, job_volunteer VARCHAR(255) DEFAULT NULL, job_refuse TINYINT(1) NOT NULL, job_from_formation TINYINT(1) NOT NULL, job_time VARCHAR(255) NOT NULL, job_not_found_other VARCHAR(255) DEFAULT NULL, degree_date VARCHAR(255) DEFAULT NULL, created_date DATETIME NOT NULL, updated_date DATETIME DEFAULT NULL, id_sectorArea INT DEFAULT NULL, INDEX IDX_E00522A0ABA8865E (sector_area_volunteer_id), INDEX IDX_E00522A0874274F0 (activity_volunteer_id), INDEX IDX_E00522A0B75B4FC (person_degree_id), INDEX IDX_E00522A0B35C5756 (degree_id), INDEX IDX_E00522A0279B02DB (id_sectorArea), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_search_activities (satisfaction_search_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_A528561668E12A1F (satisfaction_search_id), INDEX IDX_A528561681C06096 (activity_id), PRIMARY KEY(satisfaction_search_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE satisfaction_search_reasons (satisfaction_search_id INT NOT NULL, job_not_found_reason_id INT NOT NULL, INDEX IDX_ECBD438068E12A1F (satisfaction_search_id), INDEX IDX_ECBD43805C785F5D (job_not_found_reason_id), PRIMARY KEY(satisfaction_search_id, job_not_found_reason_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school (id INT AUTO_INCREMENT NOT NULL, id_city INT DEFAULT NULL, id_region INT DEFAULT NULL, id_country INT DEFAULT NULL, id_image INT DEFAULT NULL, user_id INT DEFAULT NULL, id_sector_area1 INT DEFAULT NULL, id_sector_area2 INT DEFAULT NULL, id_sector_area3 INT DEFAULT NULL, id_sector_area4 INT DEFAULT NULL, id_sector_area5 INT DEFAULT NULL, id_sector_area6 INT DEFAULT NULL, created_date DATETIME DEFAULT NULL, updated_date DATETIME DEFAULT NULL, client_updated_date DATETIME DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, agree_rgpd TINYINT(1) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, address_number INT DEFAULT NULL, address_locality VARCHAR(255) DEFAULT NULL, address_road VARCHAR(255) DEFAULT NULL, phone_standard VARCHAR(255) NOT NULL, phone_other VARCHAR(255) DEFAULT NULL, email VARCHAR(255) NOT NULL, latitude VARCHAR(255) DEFAULT NULL, longitude VARCHAR(255) DEFAULT NULL, maps_address VARCHAR(255) DEFAULT NULL, location_fixed TINYINT(1) NOT NULL, other_activity1 VARCHAR(255) DEFAULT NULL, other_activity2 VARCHAR(255) DEFAULT NULL, other_activity3 VARCHAR(255) DEFAULT NULL, other_activity4 VARCHAR(255) DEFAULT NULL, other_activity5 VARCHAR(255) DEFAULT NULL, other_activity6 VARCHAR(255) DEFAULT NULL, registration VARCHAR(255) DEFAULT NULL, other_degree VARCHAR(255) DEFAULT NULL, INDEX IDX_F99EDABBA67B1E36 (id_city), INDEX IDX_F99EDABB2955449B (id_region), INDEX IDX_F99EDABB8DEE6016 (id_country), INDEX IDX_F99EDABB2BB8456F (id_image), INDEX IDX_F99EDABBA76ED395 (user_id), INDEX IDX_F99EDABB34785B03 (id_sector_area1), INDEX IDX_F99EDABBAD710AB9 (id_sector_area2), INDEX IDX_F99EDABBDA763A2F (id_sector_area3), INDEX IDX_F99EDABB4412AF8C (id_sector_area4), INDEX IDX_F99EDABB33159F1A (id_sector_area5), INDEX IDX_F99EDABBAA1CCEA0 (id_sector_area6), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE schools_companies (school_id INT NOT NULL, company_id INT NOT NULL, INDEX IDX_F6FF96C5C32A47EE (school_id), INDEX IDX_F6FF96C5979B1AD6 (company_id), PRIMARY KEY(school_id, company_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE schools_socials (school_id INT NOT NULL, social_id INT NOT NULL, INDEX IDX_86681CE7C32A47EE (school_id), INDEX IDX_86681CE7FFEB5B27 (social_id), PRIMARY KEY(school_id, social_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_degrees1 (school_id INT NOT NULL, degree_id INT NOT NULL, INDEX IDX_97808E96C32A47EE (school_id), INDEX IDX_97808E96B35C5756 (degree_id), PRIMARY KEY(school_id, degree_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_activities1 (school_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_F3A5FC32A47EE (school_id), INDEX IDX_F3A5F81C06096 (activity_id), PRIMARY KEY(school_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_activities2 (school_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_99066BE5C32A47EE (school_id), INDEX IDX_99066BE581C06096 (activity_id), PRIMARY KEY(school_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_activities3 (school_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_EE015B73C32A47EE (school_id), INDEX IDX_EE015B7381C06096 (activity_id), PRIMARY KEY(school_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_activities4 (school_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_7065CED0C32A47EE (school_id), INDEX IDX_7065CED081C06096 (activity_id), PRIMARY KEY(school_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_activities5 (school_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_762FE46C32A47EE (school_id), INDEX IDX_762FE4681C06096 (activity_id), PRIMARY KEY(school_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_activities6 (school_id INT NOT NULL, activity_id INT NOT NULL, INDEX IDX_9E6BAFFCC32A47EE (school_id), INDEX IDX_9E6BAFFC81C06096 (activity_id), PRIMARY KEY(school_id, activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE school_degree (id_school INT NOT NULL, id_degree INT NOT NULL, INDEX IDX_5A1F6EAFDFA96F56 (id_school), INDEX IDX_5A1F6EAF8194D88E (id_degree), PRIMARY KEY(id_school, id_degree)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sector_area (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE social_network (id INT AUTO_INCREMENT NOT NULL, id_valid_social_network INT DEFAULT NULL, url VARCHAR(255) NOT NULL, INDEX IDX_EFFF522114EE1960 (id_valid_social_network), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE useful_training_reason (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_role (role_id INT NOT NULL, PRIMARY KEY(role_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE valid_social_network (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE activity_sector_area ADD CONSTRAINT FK_F742885279B02DB FOREIGN KEY (id_sectorArea) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE activity_sector_area ADD CONSTRAINT FK_F7428851782D3BB FOREIGN KEY (sector_area_id) REFERENCES sector_area (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96D81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96D2576E0FD FOREIGN KEY (contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96D979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96DA67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96D2955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96D8DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE apprentice ADD CONSTRAINT FK_54C3A96D2BB8456F FOREIGN KEY (id_image) REFERENCES image (id)');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B02342955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FA67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F2955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F8DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FD4C55DD7 FOREIGN KEY (id_contactCompany) REFERENCES contact_company (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094F279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FB4F7CA15 FOREIGN KEY (id_legal_status) REFERENCES legal_status (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE companies_socials ADD CONSTRAINT FK_B4D23109979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE companies_socials ADD CONSTRAINT FK_B4D23109FFEB5B27 FOREIGN KEY (social_id) REFERENCES social_network (id)');
        $this->addSql('ALTER TABLE contact_company ADD CONSTRAINT FK_D59028CEB954C4CC FOREIGN KEY (id_contract) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE contact_company ADD CONSTRAINT FK_D59028CE9122A03F FOREIGN KEY (id_company) REFERENCES company (id)');
        $this->addSql('ALTER TABLE contact_company ADD CONSTRAINT FK_D59028CEA67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE contact_company ADD CONSTRAINT FK_D59028CE2955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE contact_company ADD CONSTRAINT FK_D59028CE8DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE contact_company ADD CONSTRAINT FK_D59028CE2BB8456F FOREIGN KEY (id_image) REFERENCES image (id)');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966398D64AA FOREIGN KEY (id_currency) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE degree ADD CONSTRAINT FK_A7A36D6381C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE geo_location ADD CONSTRAINT FK_B027FE6AA67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE geo_location ADD CONSTRAINT FK_B027FE6A2955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE geo_location ADD CONSTRAINT FK_B027FE6A8DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE geo_location ADD CONSTRAINT FK_B027FE6A81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE geo_location ADD CONSTRAINT FK_B027FE6A279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E9122A03F FOREIGN KEY (id_company) REFERENCES company (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4ED4CE9F9E FOREIGN KEY (lasted_contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E2BB8456F FOREIGN KEY (id_image) REFERENCES image (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4EA67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E2955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4E8DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD58194D88E FOREIGN KEY (id_degree) REFERENCES degree (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD5C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD5FB063B07 FOREIGN KEY (lasted_company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD581C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD5279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD5D4CE9F9E FOREIGN KEY (lasted_contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD5A67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD52955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD58DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE person_degree ADD CONSTRAINT FK_3B065DD52BB8456F FOREIGN KEY (id_image) REFERENCES image (id)');
        $this->addSql('ALTER TABLE persons_socials ADD CONSTRAINT FK_EC688D94217BBB47 FOREIGN KEY (person_id) REFERENCES person_degree (id)');
        $this->addSql('ALTER TABLE persons_socials ADD CONSTRAINT FK_EC688D94FFEB5B27 FOREIGN KEY (social_id) REFERENCES social_network (id)');
        $this->addSql('ALTER TABLE person_degree_info_creators ADD CONSTRAINT FK_FD67B6E2B75B4FC FOREIGN KEY (person_degree_id) REFERENCES person_degree (id)');
        $this->addSql('ALTER TABLE person_degree_info_creators ADD CONSTRAINT FK_FD67B6E239E7320A FOREIGN KEY (info_creator_id) REFERENCES info_creator (id)');
        $this->addSql('ALTER TABLE publicity ADD CONSTRAINT FK_93812769122A03F FOREIGN KEY (id_company) REFERENCES company (id)');
        $this->addSql('ALTER TABLE publicity ADD CONSTRAINT FK_93812762BB8456F FOREIGN KEY (id_image) REFERENCES image (id)');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F1768DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE satisfaction_company ADD CONSTRAINT FK_D18F6915979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE satisfaction_company ADD CONSTRAINT FK_D18F6915867605F8 FOREIGN KEY (worker_sector_area_id) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE satisfaction_company ADD CONSTRAINT FK_D18F6915BAF32DF3 FOREIGN KEY (technician_sector_area_id) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE satisfaction_company_activities ADD CONSTRAINT FK_57B2A1B2B594EA25 FOREIGN KEY (satisfaction_company_id) REFERENCES satisfaction_company (id)');
        $this->addSql('ALTER TABLE satisfaction_company_activities ADD CONSTRAINT FK_57B2A1B281C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE satisfaction_company_technicians_activities ADD CONSTRAINT FK_ABA2E6BBB594EA25 FOREIGN KEY (satisfaction_company_id) REFERENCES satisfaction_company (id)');
        $this->addSql('ALTER TABLE satisfaction_company_technicians_activities ADD CONSTRAINT FK_ABA2E6BB81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE satisfaction_company_reason ADD CONSTRAINT FK_75C87BCBB594EA25 FOREIGN KEY (satisfaction_company_id) REFERENCES satisfaction_company (id)');
        $this->addSql('ALTER TABLE satisfaction_company_reason ADD CONSTRAINT FK_75C87BCB544EB073 FOREIGN KEY (omission_reason_id) REFERENCES omission_reason (id)');
        $this->addSql('ALTER TABLE satisfaction_creator ADD CONSTRAINT FK_22368A39B75B4FC FOREIGN KEY (person_degree_id) REFERENCES person_degree (id)');
        $this->addSql('ALTER TABLE satisfaction_creator ADD CONSTRAINT FK_22368A39279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE satisfaction_creator ADD CONSTRAINT FK_22368A3938248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE satisfaction_creator_activities ADD CONSTRAINT FK_92C26FBF432DFE55 FOREIGN KEY (satisfaction_creator_id) REFERENCES satisfaction_creator (id)');
        $this->addSql('ALTER TABLE satisfaction_creator_activities ADD CONSTRAINT FK_92C26FBF81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE satisfaction_creator_reasons ADD CONSTRAINT FK_B90DBFEB432DFE55 FOREIGN KEY (satisfaction_creator_id) REFERENCES satisfaction_creator (id)');
        $this->addSql('ALTER TABLE satisfaction_creator_reasons ADD CONSTRAINT FK_B90DBFEB5C785F5D FOREIGN KEY (job_not_found_reason_id) REFERENCES JobNotFoundReasonRepository (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E64276B75B4FC FOREIGN KEY (person_degree_id) REFERENCES person_degree (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E642769122A03F FOREIGN KEY (id_company) REFERENCES company (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E6427638248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E64276F2F7E833 FOREIGN KEY (job_not_found_reasons_id) REFERENCES JobNotFoundReasonRepository (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E64276D4CE9F9E FOREIGN KEY (lasted_contract_id) REFERENCES contract (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E64276279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE satisfaction_salary ADD CONSTRAINT FK_C0E6427681C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE satisfaction_search ADD CONSTRAINT FK_E00522A0ABA8865E FOREIGN KEY (sector_area_volunteer_id) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE satisfaction_search ADD CONSTRAINT FK_E00522A0874274F0 FOREIGN KEY (activity_volunteer_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE satisfaction_search ADD CONSTRAINT FK_E00522A0B75B4FC FOREIGN KEY (person_degree_id) REFERENCES person_degree (id)');
        $this->addSql('ALTER TABLE satisfaction_search ADD CONSTRAINT FK_E00522A0B35C5756 FOREIGN KEY (degree_id) REFERENCES degree (id)');
        $this->addSql('ALTER TABLE satisfaction_search ADD CONSTRAINT FK_E00522A0279B02DB FOREIGN KEY (id_sectorArea) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE satisfaction_search_activities ADD CONSTRAINT FK_A528561668E12A1F FOREIGN KEY (satisfaction_search_id) REFERENCES satisfaction_search (id)');
        $this->addSql('ALTER TABLE satisfaction_search_activities ADD CONSTRAINT FK_A528561681C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE satisfaction_search_reasons ADD CONSTRAINT FK_ECBD438068E12A1F FOREIGN KEY (satisfaction_search_id) REFERENCES satisfaction_search (id)');
        $this->addSql('ALTER TABLE satisfaction_search_reasons ADD CONSTRAINT FK_ECBD43805C785F5D FOREIGN KEY (job_not_found_reason_id) REFERENCES JobNotFoundReasonRepository (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBA67B1E36 FOREIGN KEY (id_city) REFERENCES city (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB2955449B FOREIGN KEY (id_region) REFERENCES region (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB8DEE6016 FOREIGN KEY (id_country) REFERENCES country (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB2BB8456F FOREIGN KEY (id_image) REFERENCES image (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB34785B03 FOREIGN KEY (id_sector_area1) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBAD710AB9 FOREIGN KEY (id_sector_area2) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBDA763A2F FOREIGN KEY (id_sector_area3) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB4412AF8C FOREIGN KEY (id_sector_area4) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB33159F1A FOREIGN KEY (id_sector_area5) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABBAA1CCEA0 FOREIGN KEY (id_sector_area6) REFERENCES sector_area (id)');
        $this->addSql('ALTER TABLE schools_companies ADD CONSTRAINT FK_F6FF96C5C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE schools_companies ADD CONSTRAINT FK_F6FF96C5979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE schools_socials ADD CONSTRAINT FK_86681CE7C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE schools_socials ADD CONSTRAINT FK_86681CE7FFEB5B27 FOREIGN KEY (social_id) REFERENCES social_network (id)');
        $this->addSql('ALTER TABLE school_degrees1 ADD CONSTRAINT FK_97808E96C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_degrees1 ADD CONSTRAINT FK_97808E96B35C5756 FOREIGN KEY (degree_id) REFERENCES degree (id)');
        $this->addSql('ALTER TABLE school_activities1 ADD CONSTRAINT FK_F3A5FC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_activities1 ADD CONSTRAINT FK_F3A5F81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE school_activities2 ADD CONSTRAINT FK_99066BE5C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_activities2 ADD CONSTRAINT FK_99066BE581C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE school_activities3 ADD CONSTRAINT FK_EE015B73C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_activities3 ADD CONSTRAINT FK_EE015B7381C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE school_activities4 ADD CONSTRAINT FK_7065CED0C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_activities4 ADD CONSTRAINT FK_7065CED081C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE school_activities5 ADD CONSTRAINT FK_762FE46C32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_activities5 ADD CONSTRAINT FK_762FE4681C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE school_activities6 ADD CONSTRAINT FK_9E6BAFFCC32A47EE FOREIGN KEY (school_id) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_activities6 ADD CONSTRAINT FK_9E6BAFFC81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id)');
        $this->addSql('ALTER TABLE school_degree ADD CONSTRAINT FK_5A1F6EAFDFA96F56 FOREIGN KEY (id_school) REFERENCES school (id)');
        $this->addSql('ALTER TABLE school_degree ADD CONSTRAINT FK_5A1F6EAF8194D88E FOREIGN KEY (id_degree) REFERENCES degree (id)');
        $this->addSql('ALTER TABLE social_network ADD CONSTRAINT FK_EFFF522114EE1960 FOREIGN KEY (id_valid_social_network) REFERENCES valid_social_network (id)');
        $this->addSql('ALTER TABLE user ADD country_id INT DEFAULT NULL, ADD api_token VARCHAR(255) DEFAULT NULL, ADD phone VARCHAR(255) NOT NULL, ADD valid_code VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6497BA2F5EB ON user (api_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649444F97DD ON user (phone)');
        $this->addSql('CREATE INDEX IDX_8D93D649F92F3E70 ON user (country_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE satisfaction_creator_reasons DROP FOREIGN KEY FK_B90DBFEB5C785F5D');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E64276F2F7E833');
        $this->addSql('ALTER TABLE satisfaction_search_reasons DROP FOREIGN KEY FK_ECBD43805C785F5D');
        $this->addSql('ALTER TABLE activity_sector_area DROP FOREIGN KEY FK_F742885279B02DB');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96D81C06096');
        $this->addSql('ALTER TABLE degree DROP FOREIGN KEY FK_A7A36D6381C06096');
        $this->addSql('ALTER TABLE geo_location DROP FOREIGN KEY FK_B027FE6A81C06096');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E81C06096');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD581C06096');
        $this->addSql('ALTER TABLE satisfaction_company_activities DROP FOREIGN KEY FK_57B2A1B281C06096');
        $this->addSql('ALTER TABLE satisfaction_company_technicians_activities DROP FOREIGN KEY FK_ABA2E6BB81C06096');
        $this->addSql('ALTER TABLE satisfaction_creator_activities DROP FOREIGN KEY FK_92C26FBF81C06096');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E6427681C06096');
        $this->addSql('ALTER TABLE satisfaction_search DROP FOREIGN KEY FK_E00522A0874274F0');
        $this->addSql('ALTER TABLE satisfaction_search_activities DROP FOREIGN KEY FK_A528561681C06096');
        $this->addSql('ALTER TABLE school_activities1 DROP FOREIGN KEY FK_F3A5F81C06096');
        $this->addSql('ALTER TABLE school_activities2 DROP FOREIGN KEY FK_99066BE581C06096');
        $this->addSql('ALTER TABLE school_activities3 DROP FOREIGN KEY FK_EE015B7381C06096');
        $this->addSql('ALTER TABLE school_activities4 DROP FOREIGN KEY FK_7065CED081C06096');
        $this->addSql('ALTER TABLE school_activities5 DROP FOREIGN KEY FK_762FE4681C06096');
        $this->addSql('ALTER TABLE school_activities6 DROP FOREIGN KEY FK_9E6BAFFC81C06096');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96DA67B1E36');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FA67B1E36');
        $this->addSql('ALTER TABLE contact_company DROP FOREIGN KEY FK_D59028CEA67B1E36');
        $this->addSql('ALTER TABLE geo_location DROP FOREIGN KEY FK_B027FE6AA67B1E36');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4EA67B1E36');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD5A67B1E36');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBA67B1E36');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96D979B1AD6');
        $this->addSql('ALTER TABLE companies_socials DROP FOREIGN KEY FK_B4D23109979B1AD6');
        $this->addSql('ALTER TABLE contact_company DROP FOREIGN KEY FK_D59028CE9122A03F');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E9122A03F');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD5FB063B07');
        $this->addSql('ALTER TABLE publicity DROP FOREIGN KEY FK_93812769122A03F');
        $this->addSql('ALTER TABLE satisfaction_company DROP FOREIGN KEY FK_D18F6915979B1AD6');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E642769122A03F');
        $this->addSql('ALTER TABLE schools_companies DROP FOREIGN KEY FK_F6FF96C5979B1AD6');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FD4C55DD7');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96D2576E0FD');
        $this->addSql('ALTER TABLE contact_company DROP FOREIGN KEY FK_D59028CEB954C4CC');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4ED4CE9F9E');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD5D4CE9F9E');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E64276D4CE9F9E');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96D8DEE6016');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F8DEE6016');
        $this->addSql('ALTER TABLE contact_company DROP FOREIGN KEY FK_D59028CE8DEE6016');
        $this->addSql('ALTER TABLE geo_location DROP FOREIGN KEY FK_B027FE6A8DEE6016');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E8DEE6016');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD58DEE6016');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F1768DEE6016');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB8DEE6016');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F92F3E70');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966398D64AA');
        $this->addSql('ALTER TABLE satisfaction_creator DROP FOREIGN KEY FK_22368A3938248176');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E6427638248176');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD58194D88E');
        $this->addSql('ALTER TABLE satisfaction_search DROP FOREIGN KEY FK_E00522A0B35C5756');
        $this->addSql('ALTER TABLE school_degrees1 DROP FOREIGN KEY FK_97808E96B35C5756');
        $this->addSql('ALTER TABLE school_degree DROP FOREIGN KEY FK_5A1F6EAF8194D88E');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96D2BB8456F');
        $this->addSql('ALTER TABLE contact_company DROP FOREIGN KEY FK_D59028CE2BB8456F');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E2BB8456F');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD52BB8456F');
        $this->addSql('ALTER TABLE publicity DROP FOREIGN KEY FK_93812762BB8456F');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB2BB8456F');
        $this->addSql('ALTER TABLE person_degree_info_creators DROP FOREIGN KEY FK_FD67B6E239E7320A');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FB4F7CA15');
        $this->addSql('ALTER TABLE satisfaction_company_reason DROP FOREIGN KEY FK_75C87BCB544EB073');
        $this->addSql('ALTER TABLE persons_socials DROP FOREIGN KEY FK_EC688D94217BBB47');
        $this->addSql('ALTER TABLE person_degree_info_creators DROP FOREIGN KEY FK_FD67B6E2B75B4FC');
        $this->addSql('ALTER TABLE satisfaction_creator DROP FOREIGN KEY FK_22368A39B75B4FC');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E64276B75B4FC');
        $this->addSql('ALTER TABLE satisfaction_search DROP FOREIGN KEY FK_E00522A0B75B4FC');
        $this->addSql('ALTER TABLE apprentice DROP FOREIGN KEY FK_54C3A96D2955449B');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B02342955449B');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F2955449B');
        $this->addSql('ALTER TABLE contact_company DROP FOREIGN KEY FK_D59028CE2955449B');
        $this->addSql('ALTER TABLE geo_location DROP FOREIGN KEY FK_B027FE6A2955449B');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E2955449B');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD52955449B');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB2955449B');
        $this->addSql('ALTER TABLE satisfaction_company_activities DROP FOREIGN KEY FK_57B2A1B2B594EA25');
        $this->addSql('ALTER TABLE satisfaction_company_technicians_activities DROP FOREIGN KEY FK_ABA2E6BBB594EA25');
        $this->addSql('ALTER TABLE satisfaction_company_reason DROP FOREIGN KEY FK_75C87BCBB594EA25');
        $this->addSql('ALTER TABLE satisfaction_creator_activities DROP FOREIGN KEY FK_92C26FBF432DFE55');
        $this->addSql('ALTER TABLE satisfaction_creator_reasons DROP FOREIGN KEY FK_B90DBFEB432DFE55');
        $this->addSql('ALTER TABLE satisfaction_search_activities DROP FOREIGN KEY FK_A528561668E12A1F');
        $this->addSql('ALTER TABLE satisfaction_search_reasons DROP FOREIGN KEY FK_ECBD438068E12A1F');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD5C32A47EE');
        $this->addSql('ALTER TABLE schools_companies DROP FOREIGN KEY FK_F6FF96C5C32A47EE');
        $this->addSql('ALTER TABLE schools_socials DROP FOREIGN KEY FK_86681CE7C32A47EE');
        $this->addSql('ALTER TABLE school_degrees1 DROP FOREIGN KEY FK_97808E96C32A47EE');
        $this->addSql('ALTER TABLE school_activities1 DROP FOREIGN KEY FK_F3A5FC32A47EE');
        $this->addSql('ALTER TABLE school_activities2 DROP FOREIGN KEY FK_99066BE5C32A47EE');
        $this->addSql('ALTER TABLE school_activities3 DROP FOREIGN KEY FK_EE015B73C32A47EE');
        $this->addSql('ALTER TABLE school_activities4 DROP FOREIGN KEY FK_7065CED0C32A47EE');
        $this->addSql('ALTER TABLE school_activities5 DROP FOREIGN KEY FK_762FE46C32A47EE');
        $this->addSql('ALTER TABLE school_activities6 DROP FOREIGN KEY FK_9E6BAFFCC32A47EE');
        $this->addSql('ALTER TABLE school_degree DROP FOREIGN KEY FK_5A1F6EAFDFA96F56');
        $this->addSql('ALTER TABLE activity_sector_area DROP FOREIGN KEY FK_F7428851782D3BB');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094F279B02DB');
        $this->addSql('ALTER TABLE geo_location DROP FOREIGN KEY FK_B027FE6A279B02DB');
        $this->addSql('ALTER TABLE job_offer DROP FOREIGN KEY FK_288A3A4E279B02DB');
        $this->addSql('ALTER TABLE person_degree DROP FOREIGN KEY FK_3B065DD5279B02DB');
        $this->addSql('ALTER TABLE satisfaction_company DROP FOREIGN KEY FK_D18F6915867605F8');
        $this->addSql('ALTER TABLE satisfaction_company DROP FOREIGN KEY FK_D18F6915BAF32DF3');
        $this->addSql('ALTER TABLE satisfaction_creator DROP FOREIGN KEY FK_22368A39279B02DB');
        $this->addSql('ALTER TABLE satisfaction_salary DROP FOREIGN KEY FK_C0E64276279B02DB');
        $this->addSql('ALTER TABLE satisfaction_search DROP FOREIGN KEY FK_E00522A0ABA8865E');
        $this->addSql('ALTER TABLE satisfaction_search DROP FOREIGN KEY FK_E00522A0279B02DB');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB34785B03');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBAD710AB9');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBDA763A2F');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB4412AF8C');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABB33159F1A');
        $this->addSql('ALTER TABLE school DROP FOREIGN KEY FK_F99EDABBAA1CCEA0');
        $this->addSql('ALTER TABLE companies_socials DROP FOREIGN KEY FK_B4D23109FFEB5B27');
        $this->addSql('ALTER TABLE persons_socials DROP FOREIGN KEY FK_EC688D94FFEB5B27');
        $this->addSql('ALTER TABLE schools_socials DROP FOREIGN KEY FK_86681CE7FFEB5B27');
        $this->addSql('ALTER TABLE social_network DROP FOREIGN KEY FK_EFFF522114EE1960');
        $this->addSql('DROP TABLE JobNotFoundReasonRepository');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE activity_sector_area');
        $this->addSql('DROP TABLE apprentice');
        $this->addSql('DROP TABLE candidate');
        $this->addSql('DROP TABLE candidate_research');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE companies_socials');
        $this->addSql('DROP TABLE company_creator');
        $this->addSql('DROP TABLE contact_company');
        $this->addSql('DROP TABLE contract');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE degree');
        $this->addSql('DROP TABLE geo_location');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE info_creator');
        $this->addSql('DROP TABLE job_offer');
        $this->addSql('DROP TABLE legal_status');
        $this->addSql('DROP TABLE omission_reason');
        $this->addSql('DROP TABLE person_degree');
        $this->addSql('DROP TABLE persons_socials');
        $this->addSql('DROP TABLE person_degree_info_creators');
        $this->addSql('DROP TABLE profession');
        $this->addSql('DROP TABLE publicity');
        $this->addSql('DROP TABLE reason_satisfied');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE satisfaction_company');
        $this->addSql('DROP TABLE satisfaction_company_activities');
        $this->addSql('DROP TABLE satisfaction_company_technicians_activities');
        $this->addSql('DROP TABLE satisfaction_company_reason');
        $this->addSql('DROP TABLE satisfaction_creator');
        $this->addSql('DROP TABLE satisfaction_creator_activities');
        $this->addSql('DROP TABLE satisfaction_creator_reasons');
        $this->addSql('DROP TABLE satisfaction_salary');
        $this->addSql('DROP TABLE satisfaction_search');
        $this->addSql('DROP TABLE satisfaction_search_activities');
        $this->addSql('DROP TABLE satisfaction_search_reasons');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE schools_companies');
        $this->addSql('DROP TABLE schools_socials');
        $this->addSql('DROP TABLE school_degrees1');
        $this->addSql('DROP TABLE school_activities1');
        $this->addSql('DROP TABLE school_activities2');
        $this->addSql('DROP TABLE school_activities3');
        $this->addSql('DROP TABLE school_activities4');
        $this->addSql('DROP TABLE school_activities5');
        $this->addSql('DROP TABLE school_activities6');
        $this->addSql('DROP TABLE school_degree');
        $this->addSql('DROP TABLE sector_area');
        $this->addSql('DROP TABLE social_network');
        $this->addSql('DROP TABLE useful_training_reason');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE valid_social_network');
        $this->addSql('DROP INDEX UNIQ_8D93D6497BA2F5EB ON user');
        $this->addSql('DROP INDEX UNIQ_8D93D649444F97DD ON user');
        $this->addSql('DROP INDEX IDX_8D93D649F92F3E70 ON user');
        $this->addSql('ALTER TABLE user DROP country_id, DROP api_token, DROP phone, DROP valid_code');
    }
}
