<?php

namespace App\Repository;

use App\Entity\City;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use http\QueryString;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, City::class);
	}

    public function getByRegionId(int $regionId): array {
        return $this->createQueryBuilder('c')
            ->select('c.id, c.name')
            ->where('c.region = :region')
            ->setParameter('region',$regionId)
            ->getQuery()
            ->getResult();
    }

	/**
	 * @param int $countryId
	 * @return string[]
	 */
	function getNamesByCountry(int $countryId): array {
		return $this->createQueryBuilder('city')
			->select('city.name')
			->join('city.region', 'region')
			->join('region.country', 'country')
			->where('region.country = :countryId')
			->setParameters([
				'countryId' => $countryId,
			])
			->getQuery()
			->getSingleColumnResult();
	}

	/**
	 * @param int $regionId
	 * @return string[]
	 */
	function getNamesByRegion(int $regionId): array {
		return $this->createQueryBuilder('city')
			->select('city.name')
			->join('city.region', 'region')
			->where('region.id = :regionId')
			->setParameters([
				'regionId' => $regionId,
			])
			->getQuery()
			->getSingleColumnResult();
	}
}
