<?php

namespace App\Repository;

use App\Entity\Country;
use App\Model\Template\TemplateEntity;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends ServiceEntityRepository implements ParentColumTemplateRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, Country::class);
	}

    function getNameAndIndicatif(int $id): array {
        return $this->createQueryBuilder('c')
            ->select('c.id, c.phoneCode, c.phoneDigit')
            ->where('c.id != :id')
            ->setParameters([
                'id' => $id,
            ])
            ->getQuery()
            ->getResult();
    }

	/**
	 * @return string[]
	 */
    function getCountriesByName(): array {
        return $this->createQueryBuilder('c')
            ->select('c.name')
	        ->orderBy('c.name')
            ->getQuery()
            ->getSingleColumnResult();

    }

	/**
	 * @return TemplateEntity[]
	 */
	public function getTemplateData(): array {
		return array_map(
			function (array $row): TemplateEntity {
				return new TemplateEntity((int) $row['id'], $row['name']);
			},
			$this->createQueryBuilder('c')
				->select('c.id, c.name')
                ->orderBy('c.name', 'ASC')
				->getQuery()
				->getResult()
		);
	}
}
