<?php

namespace App\Repository;

use App\Entity\JobOffer;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\Company;
use Doctrine\Persistence\ManagerRegistry;

/**
 * JobOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobOfferRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, JobOffer::class);
	}

   public function othersJobs(Company $company)
   {
      return $this->createQueryBuilder('j')
         ->where('j.company != :company')
         ->setParameter('company', $company)
         ->getQuery()
         ->getResult();
   }
}
