<?php

namespace App\Repository;

use App\Entity\JobOffer;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\Company;
use Doctrine\Persistence\ManagerRegistry;

/**
 * JobOfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobOfferRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, JobOffer::class);
	}

	/**
	 * @param Company $company
	 * @return JobOffer[]
	 */
	public function othersJobs(Company $company): array
   {
      return $this->createQueryBuilder('j')
         ->where('j.company != :company')
         ->setParameter('company', $company)
         ->getQuery()
         ->getResult();
   }

    /**
     * @return array
     */
   public function getByEmptyEndedDate() : array
   {
       return $this->createQueryBuilder('j')
           ->where('j.closedDate IS NULL')
           ->getQuery()
           ->getResult();
   }

   public function markJobOfferView(int $jobOfferId, bool $isView): void {
		$jobOffer = $this->find($jobOfferId);
		$jobOffer->setIsView($isView);

		$this->_em->persist($jobOffer);
		$this->_em->flush();
   }
}
