<?php

namespace App\Repository;

use App\Entity\Region;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, Region::class);
	}

    function getNameAndIndicatif(int $id): array {
        return $this->createQueryBuilder('r')
            ->select('r.id, r.phoneCode, r.phoneDigit')
            ->where('r.id != :id')
            ->setParameters([
                'id' => $id,
            ])
            ->getQuery()
            ->getResult();
    }
}
