<?php

namespace App\Repository;

use App\Entity\SatisfactionCompany;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\Company;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SatisfactionCompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SatisfactionCompanyRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, SatisfactionCompany::class);
	}

	/**
	 * @param Company $company
	 * @return float|int|mixed|string|null
	 * @throws \Doctrine\ORM\NonUniqueResultException
	 */
   public function getLastSatisfaction(Company $company)
   {
      return $this->createQueryBuilder('sc')
         ->select('sc')
         ->where('sc.company = :company')
         ->orderBy('sc.id', 'DESC')
         ->setParameter('company', $company)
         ->setMaxResults(1)
         ->getQuery()
         ->getOneOrNullResult();
   }
}
