<?php

namespace App\Repository;

use App\Entity\SatisfactionCreator;
use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\PersonDegree;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SatisfactionCreatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SatisfactionCreatorRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, SatisfactionCreator::class);
	}

   public function getSatisfactionCreators(PersonDegree $personDegree)
   {
      return $this->createQueryBuilder('s')
         ->select('s')
         ->where('s.personDegree = :personDegree')
         ->setParameter('personDegree', $personDegree)
         ->getQuery()
         ->getResult();
   }

   /**
    * @param PersonDegree $personDegree
    * @return mixed
    * @throws \Doctrine\ORM\NonUniqueResultException
    */
   public function getLastSatisfaction(PersonDegree $personDegree)
   {
      return $this->createQueryBuilder('sc')
         ->select('sc')
         ->where('sc.personDegree = :personDegree')
         ->orderBy('sc.id', 'DESC')
         ->setParameter('personDegree', $personDegree)
         ->setMaxResults(1)
         ->getQuery()
         ->getOneOrNullResult();
   }

}
