<?php

namespace App\Repository;

use App\Entity\SatisfactionSalary;
use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\PersonDegree;
use App\Entity\School;
use App\Entity\Country;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SatisfactionSalaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SatisfactionSalaryRepository extends ServiceEntityRepository
{
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, SatisfactionSalary::class);
	}

   /**
    * @param PersonDegree $personDegree
    * @return array
    */
   public function getSatisfactionSalaries(PersonDegree $personDegree)
   {
      return $this->createQueryBuilder('s')
         ->select('s')
         ->where('s.personDegree = :personDegree')
         ->setParameter('personDegree', $personDegree)
         ->getQuery()
         ->getResult();
   }

   /**
    * @param PersonDegree $personDegree
    * @return mixed
    * @throws \Doctrine\ORM\NonUniqueResultException
    */
   public function getLastSatisfaction(PersonDegree $personDegree)
   {
      return $this->createQueryBuilder('ss')
         ->select('ss')
         ->where('ss.personDegree = :personDegree')
         ->orderBy('ss.id', 'DESC')
         ->setParameter('personDegree', $personDegree)
         ->setMaxResults(1)
         ->getQuery()
         ->getOneOrNullResult();
   }

   /**
    * @param Country $country
    * @param School $school
    * @return array
    */
   public function getByCountryAndPersonDegreeSchool(Country $country, School $school)
   {
      return $this->createQueryBuilder('s')
         ->innerJoin('s.personDegree','pd')
         ->where('pd.country = :country ')
         ->andWhere('pd.school = :school')
         ->setParameters(['country' => $country, 'school' => $school])
         ->getQuery()
         ->getResult();
   }
}
