<?php

namespace App\Repository;

use App\Entity\School;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use App\Entity\City;
use App\Entity\Country;
use App\Entity\Region;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SchoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolRepository extends ServiceEntityRepository {
	public function __construct(ManagerRegistry $registry) {
		parent::__construct($registry, School::class);
	}

	/**
	 * @param Country $country
	 * @return School[]
	 */
	public function getNameByCountry(Country $country): array {
		return $this->createQueryBuilder('s')
			->where('s.country = :country')
			->setParameter('country', $country)
			->getQuery()
			->getResult();
	}

	/**
	 * @param Region $region
	 * @return School[]
	 */
	public function getNameByRegion(Region $region): array {
		return $this->createQueryBuilder('s')
			->where('s.region = :region')
			->setParameter('region', $region)
			->getQuery()
			->getResult();
	}

	/**
	 * @param City $city
	 * @return School[]
	 */
	public function getNameByCity(City $city): array {
		return $this->createQueryBuilder('s')
			->where('s.city = :city')
			->setParameter('city', $city)
			->getQuery()
			->getResult();
	}

	/**
	 * @param City $city
	 * @param \DateTime $createdDate
	 * @return School[]
	 */
	public function getByCityAndCreatedDate(City $city, \DateTime $createdDate): array {
		return $this->createQueryBuilder('s')
			->where('s.city = :city')
			->andWhere('s.createdDate = :createdDate')
			->setParameters(['city' => $city, 'createdDate' => $createdDate])
			->getQuery()
			->getResult();
	}

}
